/**
 * Frontend runtime configuration.
 *
 * The placeholder values below are automatically replaced with your deployed
 * resource identifiers by deployment/deploy-all.sh (Step 6) using the
 * CloudFormation stack outputs. They only exist AFTER the infrastructure is
 * deployed, so you do not edit this file by hand — the deploy script writes it
 * and uploads it to S3.
 *
 * The committed placeholders keep real account-specific IDs out of source
 * control. If you host the frontend some other way, replace the __...__
 * tokens with the matching CloudFormation output values.
 */
window.APP_CONFIG = {
    region: '__AWS_REGION__',
    userPoolId: '__USER_POOL_ID__',
    userPoolWebClientId: '__USER_POOL_CLIENT_ID__',
    identityPoolId: '__IDENTITY_POOL_ID__',
    apiUrl: '__API_URL__'
};
