default_agent: restaurant_inventory_agent
agents:
  restaurant_inventory_agent:
    name: restaurant_inventory_agent
    entrypoint: /Users/maniyes/github-repo/guidance-for-restaurant-monitoring-agents-on-aws/src/agentcore-direct/agent_inventory.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_13
    platform: linux/arm64
    container_runtime: null
    source_path: /Users/maniyes/github-repo/guidance-for-restaurant-monitoring-agents-on-aws/src/agentcore-direct
    aws:
      execution_role: arn:aws:iam::986635652628:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-72a85de11a
      execution_role_auto_create: false
      account: '986635652628'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-986635652628-us-east-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: restaurant_inventory_agent-1j0E3WFgen
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:986635652628:runtime/restaurant_inventory_agent-1j0E3WFgen
      agent_session_id: ed8159ef-74ce-4a57-9a48-74f817785aee
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
